# Generated by Django 6.0.3 on 2026-04-09 20:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('cover', models.CharField(choices=[('HARD', 'Hardcover'), ('SOFT', 'Softcover')], max_length=10)),
                ('inventory', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_fee', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
    ]
